function out = sci_palettes_list()
%%SCI_PALETTES_LIST  所有调色板名称（自动生成勿手改）
    out.categorical = {'wong','okabe_ito','duo_warm_cool','duo_blue_red', ...
                       'muted5','bright6','earth7','deep6', ...
                       'gray5','paper4','nature_soft','science_bold', ...
                       'ieee_tech','bio_dna','high_contrast8','pastel6', ...
                       'ggplot_like','dark_bright7','dark_muted6','vivid6', ...
                       'safe10','mono_blue4','mono_warm4','guofeng5', ...
                       'shuimo4','morandi6','econ5','reviewer6', ...
                       'electric8','system10'};
    out.sequential  = {'blues','oranges','greens','purples', ...
                       'reds','gray_to_blue','warm_lava','inferno_like', ...
                       'turbo_like','glacier','thermal','ocean_depth', ...
                       'plasma_like','material_blue','forest','wine', ...
                       'amber','teal_deep','violet_night','steel', ...
                       'cool_warm_seq','dark_lumen','ink_wash','cinnabar', ...
                       'bamboo','storm_current','copper_heat','aqua_density', ...
                       'graphite_gold'};
    out.diverging   = {'blue_white_red','blue_white_orange','purple_white_green','brown_white_teal', ...
                       'cool_dark_warm','aurora','cream_to_teal','teal_white_rose', ...
                       'olive_white_indigo','earth_div','berry_lime','dark_div', ...
                       'guofeng_div','voltage_balance','residual_teal_magenta','soil_sky_balance'};
    out.cyclic      = {'twilight_like','phase_classic','cyclic_isoL','phase_wheel_soft'};
end
