"""palette_export: 把调色板导出为多种格式.

支持的目标格式：
- CSS / SCSS 变量
- JSON
- LaTeX `\definecolor` 命令
- TikZ / PGFPlots 风格表
- MATLAB 矩阵字面量
- Python list 字面量
- GIMP `.gpl` palette
- ASE（Adobe Swatch Exchange，二进制简化版）

用法::

    from palette_export import export_palette
    export_palette(['#0072B2', '#D55E00'], 'css', name='mypal')
    export_palette(my_colors, 'latex', file='colors.tex')
"""
import json
import struct
from pathlib import Path
from typing import List, Union


def _to_hex(c):
    if isinstance(c, str):
        return c if c.startswith('#') else '#' + c
    return '#{:02X}{:02X}{:02X}'.format(
        int(c[0]*255+0.5), int(c[1]*255+0.5), int(c[2]*255+0.5))


def _to_rgb01(c):
    if isinstance(c, str):
        h = c.lstrip('#')
        return tuple(int(h[i:i+2], 16) / 255 for i in (0, 2, 4))
    return tuple(c)


def to_css(colors, name='palette'):
    """CSS 自定义属性."""
    out = [':root {']
    for i, c in enumerate(colors):
        out.append(f'  --{name}-{i+1}: {_to_hex(c)};')
    out.append('}')
    return '\n'.join(out)


def to_scss(colors, name='palette'):
    """SCSS 变量 + Sass list."""
    lines = []
    for i, c in enumerate(colors):
        lines.append(f'${name}-{i+1}: {_to_hex(c)};')
    lines.append(f'\n${name}: ({", ".join(_to_hex(c) for c in colors)});')
    return '\n'.join(lines)


def to_json(colors, name='palette'):
    return json.dumps({'name': name, 'colors': [_to_hex(c) for c in colors]},
                       indent=2, ensure_ascii=False)


def to_latex(colors, name='palette'):
    """`\\definecolor` 命令（HTML 模型）."""
    out = ['% generated by palette_export']
    for i, c in enumerate(colors):
        h = _to_hex(c).lstrip('#')
        out.append(f'\\definecolor{{{name}{i+1}}}{{HTML}}{{{h}}}')
    return '\n'.join(out)


def to_tikz(colors, name='palette'):
    """TikZ 风格表，可直接 \\usepgfplotslibrary{colormaps}."""
    out = [f'\\pgfplotsset{{']
    out.append(f'  cycle list/{name}/.style={{')
    out.append('    cycle list={')
    for c in colors:
        h = _to_hex(c).lstrip('#')
        out.append(f'      {{draw={{rgb,255: red,{int(h[0:2],16)}; '
                   f'green,{int(h[2:4],16)}; blue,{int(h[4:6],16)}}}}},')
    out.append('    },')
    out.append('  },')
    out.append('}')
    return '\n'.join(out)


def to_matlab(colors, name='palette'):
    """MATLAB N×3 RGB 矩阵字面量."""
    rows = [list(_to_rgb01(c)) for c in colors]
    lines = [f'{name} = [...']
    for i, r in enumerate(rows):
        end = ';' if i < len(rows) - 1 else ''
        lines.append(f'    {r[0]:.4f} {r[1]:.4f} {r[2]:.4f}{end}')
    lines.append('];')
    return '\n'.join(lines)


def to_python(colors, name='palette'):
    """Python list of hex 字面量."""
    items = ', '.join(f"'{_to_hex(c)}'" for c in colors)
    return f"{name} = [{items}]"


def to_gimp(colors, name='palette'):
    """GIMP `.gpl` palette 格式（也被 Inkscape / Krita / Aseprite 支持）."""
    out = ['GIMP Palette',
           f'Name: {name}',
           'Columns: 0',
           '#']
    for i, c in enumerate(colors):
        r, g, b = _to_rgb01(c)
        out.append(f'{int(r*255):3d} {int(g*255):3d} {int(b*255):3d}\tcolor{i+1}')
    return '\n'.join(out)


def to_ase(colors, name='palette'):
    """ASE (Adobe Swatch Exchange) 二进制格式，简化版.

    返回 bytes，可直接 write_bytes 到 .ase 文件.
    """
    out = bytearray(b'ASEF')
    out += struct.pack('>HH', 1, 0)              # version 1.0
    out += struct.pack('>I', len(colors) + 2)    # block count

    # 组开始
    name_b = name.encode('utf-16-be') + b'\x00\x00'
    block = struct.pack('>H', len(name) + 1) + name_b
    out += struct.pack('>HI', 0xC001, len(block)) + block

    for i, c in enumerate(colors):
        cname = f'{name}-{i+1}'
        nb = cname.encode('utf-16-be') + b'\x00\x00'
        r, g, b = _to_rgb01(c)
        body = struct.pack('>H', len(cname) + 1) + nb + b'RGB ' + \
               struct.pack('>fffH', r, g, b, 0)
        out += struct.pack('>HI', 0x0001, len(body)) + body

    # 组结束
    out += struct.pack('>HI', 0xC002, 0)
    return bytes(out)


FORMATS = {
    'css':    to_css,
    'scss':   to_scss,
    'json':   to_json,
    'latex':  to_latex,
    'tex':    to_latex,
    'tikz':   to_tikz,
    'matlab': to_matlab,
    'm':      to_matlab,
    'python': to_python,
    'py':     to_python,
    'gimp':   to_gimp,
    'gpl':    to_gimp,
    'ase':    to_ase,
}


def export_palette(colors, fmt, name='palette', file=None):
    """统一入口.

    file 不传 → 返回字符串/bytes
    file 传   → 写到文件并返回路径
    """
    fn = FORMATS.get(fmt.lower())
    if fn is None:
        raise ValueError(f'未知格式 {fmt}；可选: {list(FORMATS)}')
    result = fn(colors, name)
    if file is None:
        return result
    p = Path(file)
    if isinstance(result, bytes):
        p.write_bytes(result)
    else:
        p.write_text(result, encoding='utf-8')
    return p


if __name__ == '__main__':
    pal = ['#0072B2', '#D55E00', '#009E73', '#CC79A7']

    for fmt in ['css', 'scss', 'json', 'latex', 'tikz', 'matlab', 'python', 'gimp']:
        print(f'=== {fmt} ===')
        print(export_palette(pal, fmt, name='wong4'))
        print()

    # ASE 是二进制；演示输出大小
    ase = export_palette(pal, 'ase', name='wong4')
    print(f'=== ase ===\n  binary, {len(ase)} bytes')
